"""
from https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROIV6.0
# Measure BrainSeg, BrainSegVol, Brain Segmentation Volume, 1262276.000000, mm^3
# Measure BrainSegNotVent, BrainSegVolNotVent, Brain Segmentation Volume Without Ventricles, 1187271.000000, mm^3
# Measure BrainSegNotVentSurf, BrainSegVolNotVentSurf, Brain Segmentation Volume Without Ventricles from Surf, 1186951.705907, mm^3
# Measure VentricleChoroidVol, VentricleChoroidVol, Volume of ventricles and choroid plexus, 69043.000000, mm^3
# Measure lhCortex, lhCortexVol, Left hemisphere cortical gray matter volume, 259221.573235, mm^3
# Measure rhCortex, rhCortexVol, Right hemisphere cortical gray matter volume, 258713.044172, mm^3
# Measure Cortex, CortexVol, Total cortical gray matter volume, 517934.617407, mm^3
# Measure lhCerebralWhiteMatter, lhCerebralWhiteMatterVol, Left hemisphere cerebral white matter volume, 239218.899217, mm^3
# Measure rhCerebralWhiteMatter, rhCerebralWhiteMatterVol, Right hemisphere cerebral white matter volume, 236617.189283, mm^3
# Measure CerebralWhiteMatter, CerebralWhiteMatterVol, Total cerebral white matter volume, 475836.088500, mm^3
# Measure SubCortGray, SubCortGrayVol, Subcortical gray matter volume, 66911.000000, mm^3
# Measure TotalGray, TotalGrayVol, Total gray matter volume, 686541.617407, mm^3
# Measure SupraTentorial, SupraTentorialVol, Supratentorial volume, 1131346.705907, mm^3
# Measure SupraTentorialNotVent, SupraTentorialVolNotVent, Supratentorial volume, 1062303.705907, mm^3
# Measure SupraTentorialNotVentVox, SupraTentorialVolNotVentVox, Supratentorial volume voxel count, 1060851.000000, mm^3
# Measure Mask, MaskVol, Mask Volume, 1740098.000000, mm^3
# Measure BrainSegVol-to-eTIV, BrainSegVol-to-eTIV, Ratio of BrainSegVol to eTIV, 0.701763, unitless
# Measure MaskVol-to-eTIV, MaskVol-to-eTIV, Ratio of MaskVol to eTIV, 0.967408, unitless
# Measure lhSurfaceHoles, lhSurfaceHoles, Number of defect holes in lh surfaces prior to fixing, 70, unitless
# Measure rhSurfaceHoles, rhSurfaceHoles, Number of defect holes in rh surfaces prior to fixing, 59, unitless
# Measure SurfaceHoles, SurfaceHoles, Total number of defect holes in surfaces prior to fixing, 129, unitless
# Measure EstimatedTotalIntraCranialVol, eTIV, Estimated Total Intracranial Volume, 1798722.304401, mm^3
"""

expected_columns = {}
expected_columns["subcortVolume"] = ['Left-Thalamus-Proper',
                                     'Right-Thalamus-Proper', 'Left-Caudate',
                                     'Right-Caudate', 'Left-Putamen',
                                     'Right-Putamen', 'Left-Pallidum',
                                     'Right-Pallidum', 'Left-Hippocampus',
                                     'Right-Hippocampus',
                                     'Left-Amygdala', 'Right-Amygdala',
                                     'Left-Accumbens-area',
                                     'Right-Accumbens-area']

expected_columns["globalVolume"] = ['lh_MeanThickness_thickness',
                                    'rh_MeanThickness_thickness',
                                    '3rd-Ventricle', '4th-Ventricle',
                                    'Left-Lateral-Ventricle',
                                    'Right-Lateral-Ventricle', 'lhCortexVol',
                                    'rhCortexVol',
                                    'lhCerebralWhiteMatterVol',
                                    'rhCerebralWhiteMatterVol',
                                    'Left-Cerebellum-White-Matter',
                                    'Right-Cerebellum-White-Matter',
                                    'Left-Cerebellum-Cortex',
                                    'Right-Cerebellum-Cortex',
                                    'CC_Posterior', 'CC_Mid_Posterior',
                                    'CC_Central',
                                    'CC_Mid_Anterior', 'CC_Anterior',
                                    'SubCortGrayVol', 'TotalGrayVol']

expected_columns["cortVolume"] = ['lh_G_S_frontomargin_volume',
                                  'lh_G_S_occipital_inf_volume',
                                  'lh_G_S_paracentral_volume',
                                  'lh_G_S_subcentral_volume',
                                  'lh_G_S_transv_frontopol_volume',
                                  'lh_G_S_cingul-Ant_volume',
                                  'lh_G_S_cingul-Mid-Ant_volume',
                                  'lh_G_S_cingul-Mid-Post_volume',
                                  'lh_G_cingul-Post-dorsal_volume',
                                  'lh_G_cingul-Post-ventral_volume',
                                  'lh_G_cuneus_volume',
                                  'lh_G_front_inf-Opercular_volume',
                                  'lh_G_front_inf-Orbital_volume',
                                  'lh_G_front_inf-Triangul_volume',
                                  'lh_G_front_middle_volume',
                                  'lh_G_front_sup_volume',
                                  'lh_G_Ins_lg_S_cent_ins_volume',
                                  'lh_G_insular_short_volume',
                                  'lh_G_occipital_middle_volume',
                                  'lh_G_occipital_sup_volume',
                                  'lh_G_oc-temp_lat-fusifor_volume',
                                  'lh_G_oc-temp_med-Lingual_volume',
                                  'lh_G_oc-temp_med-Parahip_volume',
                                  'lh_G_orbital_volume',
                                  'lh_G_pariet_inf-Angular_volume',
                                  'lh_G_pariet_inf-Supramar_volume',
                                  'lh_G_parietal_sup_volume',
                                  'lh_G_postcentral_volume',
                                  'lh_G_precentral_volume',
                                  'lh_G_precuneus_volume',
                                  'lh_G_rectus_volume',
                                  'lh_G_subcallosal_volume',
                                  'lh_G_temp_sup-G_T_transv_volume',
                                  'lh_G_temp_sup-Lateral_volume',
                                  'lh_G_temp_sup-Plan_polar_volume',
                                  'lh_G_temp_sup-Plan_tempo_volume',
                                  'lh_G_temporal_inf_volume',
                                  'lh_G_temporal_middle_volume',
                                  'lh_Lat_Fis-ant-Horizont_volume',
                                  'lh_Lat_Fis-ant-Vertical_volume',
                                  'lh_Lat_Fis-post_volume',
                                  'lh_Pole_occipital_volume',
                                  'lh_Pole_temporal_volume',
                                  'lh_S_calcarine_volume',
                                  'lh_S_central_volume',
                                  'lh_S_cingul-Marginalis_volume',
                                  'lh_S_circular_insula_ant_volume',
                                  'lh_S_circular_insula_inf_volume',
                                  'lh_S_circular_insula_sup_volume',
                                  'lh_S_collat_transv_ant_volume',
                                  'lh_S_collat_transv_post_volume',
                                  'lh_S_front_inf_volume',
                                  'lh_S_front_middle_volume',
                                  'lh_S_front_sup_volume',
                                  'lh_S_interm_prim-Jensen_volume',
                                  'lh_S_intrapariet_P_trans_volume',
                                  'lh_S_oc_middle_Lunatus_volume',
                                  'lh_S_oc_sup_transversal_volume',
                                  'lh_S_occipital_ant_volume',
                                  'lh_S_oc-temp_lat_volume',
                                  'lh_S_oc-temp_med_Lingual_volume',
                                  'lh_S_orbital_lateral_volume',
                                  'lh_S_orbital_med-olfact_volume',
                                  'lh_S_orbital-H_Shaped_volume',
                                  'lh_S_parieto_occipital_volume',
                                  'lh_S_pericallosal_volume',
                                  'lh_S_postcentral_volume',
                                  'lh_S_precentral-inf-part_volume',
                                  'lh_S_precentral-sup-part_volume',
                                  'lh_S_suborbital_volume',
                                  'lh_S_subparietal_volume',
                                  'lh_S_temporal_inf_volume',
                                  'lh_S_temporal_sup_volume',
                                  'lh_S_temporal_transverse_volume',
                                  'rh_G_S_frontomargin_volume',
                                  'rh_G_S_occipital_inf_volume',
                                  'rh_G_S_paracentral_volume',
                                  'rh_G_S_subcentral_volume',
                                  'rh_G_S_transv_frontopol_volume',
                                  'rh_G_S_cingul-Ant_volume',
                                  'rh_G_S_cingul-Mid-Ant_volume',
                                  'rh_G_S_cingul-Mid-Post_volume',
                                  'rh_G_cingul-Post-dorsal_volume',
                                  'rh_G_cingul-Post-ventral_volume',
                                  'rh_G_cuneus_volume',
                                  'rh_G_front_inf-Opercular_volume',
                                  'rh_G_front_inf-Orbital_volume',
                                  'rh_G_front_inf-Triangul_volume',
                                  'rh_G_front_middle_volume',
                                  'rh_G_front_sup_volume',
                                  'rh_G_Ins_lg_S_cent_ins_volume',
                                  'rh_G_insular_short_volume',
                                  'rh_G_occipital_middle_volume',
                                  'rh_G_occipital_sup_volume',
                                  'rh_G_oc-temp_lat-fusifor_volume',
                                  'rh_G_oc-temp_med-Lingual_volume',
                                  'rh_G_oc-temp_med-Parahip_volume',
                                  'rh_G_orbital_volume',
                                  'rh_G_pariet_inf-Angular_volume',
                                  'rh_G_pariet_inf-Supramar_volume',
                                  'rh_G_parietal_sup_volume',
                                  'rh_G_postcentral_volume',
                                  'rh_G_precentral_volume',
                                  'rh_G_precuneus_volume',
                                  'rh_G_rectus_volume',
                                  'rh_G_subcallosal_volume',
                                  'rh_G_temp_sup-G_T_transv_volume',
                                  'rh_G_temp_sup-Lateral_volume',
                                  'rh_G_temp_sup-Plan_polar_volume',
                                  'rh_G_temp_sup-Plan_tempo_volume',
                                  'rh_G_temporal_inf_volume',
                                  'rh_G_temporal_middle_volume',
                                  'rh_Lat_Fis-ant-Horizont_volume',
                                  'rh_Lat_Fis-ant-Vertical_volume',
                                  'rh_Lat_Fis-post_volume',
                                  'rh_Pole_occipital_volume',
                                  'rh_Pole_temporal_volume',
                                  'rh_S_calcarine_volume',
                                  'rh_S_central_volume',
                                  'rh_S_cingul-Marginalis_volume',
                                  'rh_S_circular_insula_ant_volume',
                                  'rh_S_circular_insula_inf_volume',
                                  'rh_S_circular_insula_sup_volume',
                                  'rh_S_collat_transv_ant_volume',
                                  'rh_S_collat_transv_post_volume',
                                  'rh_S_front_inf_volume',
                                  'rh_S_front_middle_volume',
                                  'rh_S_front_sup_volume',
                                  'rh_S_interm_prim-Jensen_volume',
                                  'rh_S_intrapariet_P_trans_volume',
                                  'rh_S_oc_middle_Lunatus_volume',
                                  'rh_S_oc_sup_transversal_volume',
                                  'rh_S_occipital_ant_volume',
                                  'rh_S_oc-temp_lat_volume',
                                  'rh_S_oc-temp_med_Lingual_volume',
                                  'rh_S_orbital_lateral_volume',
                                  'rh_S_orbital_med-olfact_volume',
                                  'rh_S_orbital-H_Shaped_volume',
                                  'rh_S_parieto_occipital_volume',
                                  'rh_S_pericallosal_volume',
                                  'rh_S_postcentral_volume',
                                  'rh_S_precentral-inf-part_volume',
                                  'rh_S_precentral-sup-part_volume',
                                  'rh_S_suborbital_volume',
                                  'rh_S_subparietal_volume',
                                  'rh_S_temporal_inf_volume',
                                  'rh_S_temporal_sup_volume',
                                  'rh_S_temporal_transverse_volume']

expected_columns["cortThickness"] = ['lh_G_S_frontomargin_thickness',
                                     'lh_G_S_occipital_inf_thickness',
                                     'lh_G_S_paracentral_thickness',
                                     'lh_G_S_subcentral_thickness',
                                     'lh_G_S_transv_frontopol_thickness',
                                     'lh_G_S_cingul-Ant_thickness',
                                     'lh_G_S_cingul-Mid-Ant_thickness',
                                     'lh_G_S_cingul-Mid-Post_thickness',
                                     'lh_G_cingul-Post-dorsal_thickness',
                                     'lh_G_cingul-Post-ventral_thickness',
                                     'lh_G_cuneus_thickness',
                                     'lh_G_front_inf-Opercular_thickness',
                                     'lh_G_front_inf-Orbital_thickness',
                                     'lh_G_front_inf-Triangul_thickness',
                                     'lh_G_front_middle_thickness',
                                     'lh_G_front_sup_thickness',
                                     'lh_G_Ins_lg_S_cent_ins_thickness',
                                     'lh_G_insular_short_thickness',
                                     'lh_G_occipital_middle_thickness',
                                     'lh_G_occipital_sup_thickness',
                                     'lh_G_oc-temp_lat-fusifor_thickness',
                                     'lh_G_oc-temp_med-Lingual_thickness',
                                     'lh_G_oc-temp_med-Parahip_thickness',
                                     'lh_G_orbital_thickness',
                                     'lh_G_pariet_inf-Angular_thickness',
                                     'lh_G_pariet_inf-Supramar_thickness',
                                     'lh_G_parietal_sup_thickness',
                                     'lh_G_postcentral_thickness',
                                     'lh_G_precentral_thickness',
                                     'lh_G_precuneus_thickness',
                                     'lh_G_rectus_thickness',
                                     'lh_G_subcallosal_thickness',
                                     'lh_G_temp_sup-G_T_transv_thickness',
                                     'lh_G_temp_sup-Lateral_thickness',
                                     'lh_G_temp_sup-Plan_polar_thickness',
                                     'lh_G_temp_sup-Plan_tempo_thickness',
                                     'lh_G_temporal_inf_thickness',
                                     'lh_G_temporal_middle_thickness',
                                     'lh_Lat_Fis-ant-Horizont_thickness',
                                     'lh_Lat_Fis-ant-Vertical_thickness',
                                     'lh_Lat_Fis-post_thickness',
                                     'lh_Pole_occipital_thickness',
                                     'lh_Pole_temporal_thickness',
                                     'lh_S_calcarine_thickness',
                                     'lh_S_central_thickness',
                                     'lh_S_cingul-Marginalis_thickness',
                                     'lh_S_circular_insula_ant_thickness',
                                     'lh_S_circular_insula_inf_thickness',
                                     'lh_S_circular_insula_sup_thickness',
                                     'lh_S_collat_transv_ant_thickness',
                                     'lh_S_collat_transv_post_thickness',
                                     'lh_S_front_inf_thickness',
                                     'lh_S_front_middle_thickness',
                                     'lh_S_front_sup_thickness',
                                     'lh_S_interm_prim-Jensen_thickness',
                                     'lh_S_intrapariet_P_trans_thickness',
                                     'lh_S_oc_middle_Lunatus_thickness',
                                     'lh_S_oc_sup_transversal_thickness',
                                     'lh_S_occipital_ant_thickness',
                                     'lh_S_oc-temp_lat_thickness',
                                     'lh_S_oc-temp_med_Lingual_thickness',
                                     'lh_S_orbital_lateral_thickness',
                                     'lh_S_orbital_med-olfact_thickness',
                                     'lh_S_orbital-H_Shaped_thickness',
                                     'lh_S_parieto_occipital_thickness',
                                     'lh_S_pericallosal_thickness',
                                     'lh_S_postcentral_thickness',
                                     'lh_S_precentral-inf-part_thickness',
                                     'lh_S_precentral-sup-part_thickness',
                                     'lh_S_suborbital_thickness',
                                     'lh_S_subparietal_thickness',
                                     'lh_S_temporal_inf_thickness',
                                     'lh_S_temporal_sup_thickness',
                                     'lh_S_temporal_transverse_thickness',
                                     'rh_G_S_frontomargin_thickness',
                                     'rh_G_S_occipital_inf_thickness',
                                     'rh_G_S_paracentral_thickness',
                                     'rh_G_S_subcentral_thickness',
                                     'rh_G_S_transv_frontopol_thickness',
                                     'rh_G_S_cingul-Ant_thickness',
                                     'rh_G_S_cingul-Mid-Ant_thickness',
                                     'rh_G_S_cingul-Mid-Post_thickness',
                                     'rh_G_cingul-Post-dorsal_thickness',
                                     'rh_G_cingul-Post-ventral_thickness',
                                     'rh_G_cuneus_thickness',
                                     'rh_G_front_inf-Opercular_thickness',
                                     'rh_G_front_inf-Orbital_thickness',
                                     'rh_G_front_inf-Triangul_thickness',
                                     'rh_G_front_middle_thickness',
                                     'rh_G_front_sup_thickness',
                                     'rh_G_Ins_lg_S_cent_ins_thickness',
                                     'rh_G_insular_short_thickness',
                                     'rh_G_occipital_middle_thickness',
                                     'rh_G_occipital_sup_thickness',
                                     'rh_G_oc-temp_lat-fusifor_thickness',
                                     'rh_G_oc-temp_med-Lingual_thickness',
                                     'rh_G_oc-temp_med-Parahip_thickness',
                                     'rh_G_orbital_thickness',
                                     'rh_G_pariet_inf-Angular_thickness',
                                     'rh_G_pariet_inf-Supramar_thickness',
                                     'rh_G_parietal_sup_thickness',
                                     'rh_G_postcentral_thickness',
                                     'rh_G_precentral_thickness',
                                     'rh_G_precuneus_thickness',
                                     'rh_G_rectus_thickness',
                                     'rh_G_subcallosal_thickness',
                                     'rh_G_temp_sup-G_T_transv_thickness',
                                     'rh_G_temp_sup-Lateral_thickness',
                                     'rh_G_temp_sup-Plan_polar_thickness',
                                     'rh_G_temp_sup-Plan_tempo_thickness',
                                     'rh_G_temporal_inf_thickness',
                                     'rh_G_temporal_middle_thickness',
                                     'rh_Lat_Fis-ant-Horizont_thickness',
                                     'rh_Lat_Fis-ant-Vertical_thickness',
                                     'rh_Lat_Fis-post_thickness',
                                     'rh_Pole_occipital_thickness',
                                     'rh_Pole_temporal_thickness',
                                     'rh_S_calcarine_thickness',
                                     'rh_S_central_thickness',
                                     'rh_S_cingul-Marginalis_thickness',
                                     'rh_S_circular_insula_ant_thickness',
                                     'rh_S_circular_insula_inf_thickness',
                                     'rh_S_circular_insula_sup_thickness',
                                     'rh_S_collat_transv_ant_thickness',
                                     'rh_S_collat_transv_post_thickness',
                                     'rh_S_front_inf_thickness',
                                     'rh_S_front_middle_thickness',
                                     'rh_S_front_sup_thickness',
                                     'rh_S_interm_prim-Jensen_thickness',
                                     'rh_S_intrapariet_P_trans_thickness',
                                     'rh_S_oc_middle_Lunatus_thickness',
                                     'rh_S_oc_sup_transversal_thickness',
                                     'rh_S_occipital_ant_thickness',
                                     'rh_S_oc-temp_lat_thickness',
                                     'rh_S_oc-temp_med_Lingual_thickness',
                                     'rh_S_orbital_lateral_thickness',
                                     'rh_S_orbital_med-olfact_thickness',
                                     'rh_S_orbital-H_Shaped_thickness',
                                     'rh_S_parieto_occipital_thickness',
                                     'rh_S_pericallosal_thickness',
                                     'rh_S_postcentral_thickness',
                                     'rh_S_precentral-inf-part_thickness',
                                     'rh_S_precentral-sup-part_thickness',
                                     'rh_S_suborbital_thickness',
                                     'rh_S_subparietal_thickness',
                                     'rh_S_temporal_inf_thickness',
                                     'rh_S_temporal_sup_thickness',
                                     'rh_S_temporal_transverse_thickness']

for k, v in expected_columns.items():
    expected_columns[k] = [f"fs__{k}__{c}" for c in v]

if __name__ == "__main__":
    header = """ N | name
    ---|---\n"""
    s = ""
    for k, labels in expected_columns.items():
        s += f"## {k}\n"
        s += f"{len(labels)} regions\n\n"
        s += header
        for i, l in enumerate(labels, 1):
            s+= f"{i}|{l}\n"
        s += "\n\n\n"
    print(s)

